server:
  port: 8083
  servlet:
    context-path: /coder

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://hw1.nb6868.com:3306/onex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: onex
      password: onex
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/

# mybatis plus
# see {https://mybatis.plus/config/}
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.nb6868.onexcoder.entity
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 字段策略
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      # 逻辑删除配置
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    # 关闭mp3.0自带的banner
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
database: mysql
